title: UMD FIRE SPD
description: 
description: 
  Simulated Particle Detection lab analyzing HGCAL data 
  <br><br>
  <a href=https://www.fire.umd.edu/spd</a> 
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
