title: Müge Karagöz, PhD
logo: assets/img/Muge-Karagoz.jpg
description: 
description: 
  Committed and experienced researcher and educator with a 20+ years of history of working in large research collaborations and leading institutions. 
  <br><br>
  <a href="https://www.linkedin.com/in/mugekaragoz/">View My LinkedIn Profile</a> 
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
